import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by VISWA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  function handleTabChange(arg0: string): void {
    throw new Error("Function not implemented.");
  }

  return (
    <html lang="en">

      <head>

      </head>
      <body className={inter.className}>

        {children}</body>
    </html>
  );
}
